"""empty message

Revision ID: 043b3ef0791b
Revises: 760e62db5a2c
Create Date: 2020-04-10 20:28:12.304315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043b3ef0791b'
down_revision = '760e62db5a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remaining_employees', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('remaining_employees_admin_id_key', 'remaining_employees', type_='unique')
    op.create_unique_constraint(None, 'remaining_employees', ['company_id'])
    op.drop_constraint('remaining_employees_admin_id_fkey', 'remaining_employees', type_='foreignkey')
    op.create_foreign_key(None, 'remaining_employees', 'companies', ['company_id'], ['id'])
    op.drop_column('remaining_employees', 'admin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remaining_employees', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'remaining_employees', type_='foreignkey')
    op.create_foreign_key('remaining_employees_admin_id_fkey', 'remaining_employees', 'users', ['admin_id'], ['id'])
    op.drop_constraint(None, 'remaining_employees', type_='unique')
    op.create_unique_constraint('remaining_employees_admin_id_key', 'remaining_employees', ['admin_id'])
    op.drop_column('remaining_employees', 'company_id')
    # ### end Alembic commands ###
