"""empty message

Revision ID: 760e62db5a2c
Revises: a2a88c210fbd
Create Date: 2020-04-10 02:51:08.880971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760e62db5a2c'
down_revision = 'a2a88c210fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'remaining_employees', ['admin_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'remaining_employees', type_='unique')
    # ### end Alembic commands ###
