"""empty message

Revision ID: a2a88c210fbd
Revises: 7e1baccf7422
Create Date: 2020-04-09 21:46:08.659157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a88c210fbd'
down_revision = '7e1baccf7422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'addresses', ['address_id'], ['id'])
    op.add_column('remaining_employees', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'remaining_employees', 'users', ['admin_id'], ['id'])
    op.add_column('users', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['admin_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'manager_id')
    op.drop_column('users', 'company_id')
    op.drop_column('users', 'admin_id')
    op.drop_constraint(None, 'remaining_employees', type_='foreignkey')
    op.drop_column('remaining_employees', 'admin_id')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'address_id')
    # ### end Alembic commands ###
