"""empty message

Revision ID: c4879216ac88
Revises: 043b3ef0791b
Create Date: 2020-04-10 22:13:49.662609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4879216ac88'
down_revision = '043b3ef0791b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
